openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-15
    description: 'Public web api'
paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/endpoints:
    summary: get all endpoints
    description: Get all enpoints
    get:
      operationId: 'getEndpoints'
      tags:
        - Endpoint
      responses:
        '200':
          description: list of all endpoints
          content:
            text/json:
              schema:
                type: array
                items:
                  type: object
                example: [ {
                  id: '1',
                  name: 'Endpoint home',
                  available: true,
                  location: 'here',
                  privateEndpoint: true
                }]
        '401':
          description: Authorization information is missing or invalid.
        '5XX':
          description: Unexpected error.
  /api/endpoints/{id}:
    summary: get endpoint information
    description: get endpoint information from ID
    get:
      tags:
        - endpoint
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: give the id of the endpoint
      responses:
        '200':
          description: list of an endpoint given their id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  available:
                    type: boolean
                  location:
                    type: string
                  privateEndpoint:
                    type: boolean
        '401':
          description: Authorization information is missing or invalid.
        '5XX':
          description: Unexpected error.